### ISSUE TITLE
seedll/aliyunpan 能否支持软件升级？

### ISSUE THREAD

**Issue by gzxiexl** [SeeDLL/Ubuntu_Docker#2]
aliyunpan目前最新的版本是v3.11.22，docker镜像能否支持软件升级？或者重新创建后支持自动更新到最新版 ，谢谢大佬

**Comment by gzxiexl** [comment]
可以支持添加变量ALIYUNPAN_VER=

**Comment by SeeDLL** [comment]
最近暂时不太行，是因为aliyunpan那边的releases的版本号每一次更新都是不确定的，所以他的最新版本的下载链接也是不确定的，下载链接跟随版本号变动。

至于你说的添加版本号变量，我曾经也尝试过，，但有一个版本，遭遇到版本号不带v这个前缀的下载链接，然后就下载失败，所以版本号变量这个就pass了。

当然，也可以用py或者shell脚本到releases页面去自动分析最新的版本号，只是最近一段时间不太可能有时间来写这个代码，所以现在是采用的直接使用他最新版本的连接来打包的。

另外，这个aliyunpan的docker打包项目，现在已经迁移到另一个项目仓库了，地址是这个：[https://github.com/SeeDLL-Docker/Aliyunpan](https://github.com/SeeDLL-Docker/Aliyunpan)。

至于这个仓库里的其他打包项目，也会逐步迁移到上述的这个项目里，已经被迁移走的，这个仓库里就会逐步删除，并留有新的项目仓库地址。
